name: dart_personal_website_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

dependencies:
 flutter:
   sdk: flutter
 shelf: ^1.4.2
 shelf_router: ^1.1.2
 shelf_static: ^1.1.3
 url_launcher: ^6.3.0
  

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6

flutter:
 uses-material-design: true