name: dart_personal_website_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.3.3
  pdf: ^3.11.3
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_static: ^1.1.3
  url_launcher: ^6.3.0
  web: ^1.1.1


dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6

flutter:
  uses-material-design: true
  assets:
    # other pics
    - assets/qrCode.png
    - assets/me.jpg
    # docs
    - assets/dco1.webp
    - assets/dco2.webp
    - assets/dco3.webp
    - assets/dco4.webp
    - assets/photo1.webp
    - assets/photo2.webp
    - assets/photo3.webp
    - assets/photo4.webp
    - assets/photo5.webp
    - assets/photo6.webp
    - assets/photo7.webp
    - assets/photo8.webp
    - assets/photo9.webp
    - assets/photo10.webp
    - assets/photo11.webp
    - assets/photo12.webp
    - assets/photo13.webp
    - assets/photo14.webp
    - assets/photo15.webp
    - assets/photo16.webp
    - assets/photo17.webp
    - assets/photo18.webp
    - assets/photo19.webp
    - assets/photo20.webp
    - assets/photo21.webp
    # apps icons
    - assets/appcradleplayer.png
    - assets/activity.webp
    - assets/flutter.png
    - assets/appcradleicon.jpeg
    - assets/feelingsdiary.webp
    - assets/tasktime.webp
    - assets/workinghours.webp
    - assets/wot.webp
    - assets/model.pdf
